remote_theme: kerim/academic

# General settings
title: P. Kerim Friedman 傅可恩
description:
  zh: 國立東華大學的副教授
  en: Associate Professor at National Dong Hwa University, TAIWAN
baseurl: "/digitalgarden/"
url: "https://kerim.oxus.net"

langs: ["zh", "en"]
defaults:
  - scope:
      path: ""
    values:
      lang: "zh"

# Author
author: P. Kerim Friedman 傅可恩

email: fulaoshi@gms.ndhu.edu.tw
github_username: kerim
twitter_username: kerim
author_display: homepage
author_website: http://kerim.oxus.net/digitalgarden/
curriculum: 
  name: Reserchgate
  url: https://www.researchgate.net/profile/P-Friedman

# Nav menu

nav_ext_links:
  - name: Blog
    url:
      zh: http://keywords.oxus.net
      en: http://keywords.oxus.net
  - name: Teaching
    url: 
      zh: http://kerim.oxus.net/syllabi
      en: http://kerim.oxus.net/syllabi

# Favicon
favicon:
  safari: 5bbad5
  theme: ffffff

