remote_theme: kerim/academic

# General settings
title: P. Kerim Friedman 傅可恩
description:
  en: Kerim is a Taiwan-based anthropologist.
  zh: 傅可恩
baseurl: "/digitalgarden/"
url: "https://kerim.oxus.net"

langs: ["en", "zh"]
defaults:
  - scope:
      path: ""
    values:
      lang: "en"

# Author
author: P. Kerim Friedman 傅可恩
email: fulaoshi@gms.ndhu.edu.tw
github_username: kerim
twitter_username: kerim
facebook_username: kerim.friedman
curriculum: 
  name: ResearchGate
  url: https://www.researchgate.net/profile/P_Friedman

# Nav menu

nav_ext_links:
  - name: Blog
    url:
      zh: http://keywords.oxus.net
      en: http://keywords.oxus.net
  - name: Teaching
    url: 
      zh: http://kerim.oxus.net/syllabi
      en: http://kerim.oxus.net/syllabi

# Favicon
favicon:
  safari: 5bbad5
  theme: ffffff

