remote_theme: kerim/academic

# General settings
title: P. Kerim Friedman 傅可恩
description:
  zh: 國立東華大學的副教授
  en: Associate Professor at National Dong Hwa University, Taiwan
baseurl: ""
url: "https://kerim.oxus.net/digitalgarden/"

langs: ["zh", "en"]
defaults:
  - scope:
      path: ""
    values:
      lang: "zh"

# Author
author: P. Kerim Friedman 傅可恩

email: fulaoshi@gms.ndhu.edu.tw
twitter_username: kerim
author_website: http://kerim.oxus.net/
curriculum:
  url: https://sys.ndhu.edu.tw/RD/TeacherTreasury/tlist.aspx?tcher=10904

# Nav menu
nav_ext_links:
  - name: Blog
    url:
      zh: http://keywords.oxus.net/
      en: http://keywords.oxus.net/

# Favicon
favicon:
  safari: 5bbad5
  theme: ffffff

