remote_theme: kerim/academic

# General settings
title: P. Kerim Friedman 傅可恩
description:
  en: Associate Professor at the Department of Ethnic Relations and Cultures, National Dong Hwa University, TAIWAN
  zh: 副教授，國立東華大學，族群關係與文化學系
baseurl: "/digitalgarden/"
url: "https://kerim.oxus.net"

langs: ["en", "zh"]
defaults:
  - scope:
      path: ""
    values:
      lang: "zh"

# Author
author: P. Kerim Friedman 傅可恩

email: fulaoshi@gms.ndhu.edu.tw
github_username: kerim
twitter_username: kerim
curriculum: 
  name: home
  url: https://kerim.oxus.net/digitalgarden/

# Nav menu

nav_ext_links:
  - name: Blog
    url:
      zh: http://keywords.oxus.net
      en: http://keywords.oxus.net
  - name: Teaching
    url: 
      zh: http://kerim.oxus.net/syllabi
      en: http://kerim.oxus.net/syllabi

# Favicon
favicon:
  safari: 5bbad5
  theme: ffffff

