remote_theme: kerim/academic
title: P. Kerim Friedman 傅可恩
description: Photo by Darren Melrose
logo: images/avatar.jpg
show_downloads: false
email: fulaoshi@gms.ndhu.edu.tw
name: ResearchGate Profile
url: https://www.researchgate.net/profile/P-Friedman
shortbio: Associate Professor at National Dong Hwa University, Taiwan
author_display: true
author_website: true
twitter_username: kerim
