remote_theme: kerim/academic

# General settings
title: P. Kerim Friedman 傅可恩
description: Kerim is a Taiwan-based anthropologist. 傅老師是一個在台灣的人類學家. Now???
baseurl: "/digitalgarden/"
url: "https://kerim.oxus.net"

# Author
author: P. Kerim Friedman 傅可恩
email: fulaoshi@gms.ndhu.edu.tw
github_username: kerim
twitter_username: kerim
facebook_username: kerim.friedman

# Nav menu

nav_ext_links:
  - name: Blog
    url: http://keywords.oxus.net
  - name: Teaching
    url: http://kerim.oxus.net/syllabi

# Favicon
favicon:
  safari: 5bbad5
  theme: ffffff

