remote_theme: kerim/academic

# General settings
title: P. Kerim Friedman 傅可恩
description:
  zh: 國立東華大學的副教授
  en: Associate Professor at National Dong Hwa University, Taiwan
baseurl: "/digitalgarden/"
url: "https://kerim.oxus.net"

langs: ["zh", "en"]
defaults:
  - scope:
      path: ""
    values:
      lang: "zh"

# Author
author: P. Kerim Friedman 傅可恩

email: fulaoshi@gms.ndhu.edu.tw
github_username: kerim
twitter_username: kerim
author_website: http://kerim.oxus.net/digitalgarden/
curriculum: Reserchgate
  url: https://www.researchgate.net/profile/P-Friedman

# Nav menu
nav_ext_links:
  - name: Blog
   url:  http://keywords.oxus.net/
  - name: Teaching
    url:  http://kerim.oxus.net/syllabi
  zh: https://kerim.oxus.net/chinese.html
  en: http://kerim.oxus.net/digitalgarden

# Favicon
favicon:
  safari: 5bbad5
  theme: ffffff

